/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthRegisterInstituteRouteImport } from './routes/auth/register-institute'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardSuperAdminIndexRouteImport } from './routes/dashboard/super-admin/index'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard/student/index'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard/staff/index'
import { Route as DashboardParentIndexRouteImport } from './routes/dashboard/parent/index'
import { Route as DashboardAnalyticsIndexRouteImport } from './routes/dashboard/analytics/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardStaffStudentsIndexRouteImport } from './routes/dashboard/staff/students/index'
import { Route as DashboardAdminStudyLogsIndexRouteImport } from './routes/dashboard/admin/study-logs/index'
import { Route as DashboardAdminStudentsIndexRouteImport } from './routes/dashboard/admin/students/index'
import { Route as DashboardAdminStaffIndexRouteImport } from './routes/dashboard/admin/staff/index'
import { Route as DashboardAdminScheduleIndexRouteImport } from './routes/dashboard/admin/schedule/index'
import { Route as DashboardAdminParentsIndexRouteImport } from './routes/dashboard/admin/parents/index'
import { Route as DashboardAdminFeesIndexRouteImport } from './routes/dashboard/admin/fees/index'
import { Route as DashboardAdminBatchesIndexRouteImport } from './routes/dashboard/admin/batches/index'
import { Route as DashboardAdminAttendanceIndexRouteImport } from './routes/dashboard/admin/attendance/index'
import { Route as DashboardStaffStudentsStudentIdRouteImport } from './routes/dashboard/staff/students/$studentId'
import { Route as DashboardAdminStudentsStudentIdRouteImport } from './routes/dashboard/admin/students/$studentId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterInstituteRoute = AuthRegisterInstituteRouteImport.update({
  id: '/auth/register-institute',
  path: '/auth/register-institute',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSuperAdminIndexRoute =
  DashboardSuperAdminIndexRouteImport.update({
    id: '/super-admin/',
    path: '/super-admin/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParentIndexRoute = DashboardParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsIndexRoute = DashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffStudentsIndexRoute =
  DashboardStaffStudentsIndexRouteImport.update({
    id: '/staff/students/',
    path: '/staff/students/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStudyLogsIndexRoute =
  DashboardAdminStudyLogsIndexRouteImport.update({
    id: '/admin/study-logs/',
    path: '/admin/study-logs/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStudentsIndexRoute =
  DashboardAdminStudentsIndexRouteImport.update({
    id: '/admin/students/',
    path: '/admin/students/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStaffIndexRoute =
  DashboardAdminStaffIndexRouteImport.update({
    id: '/admin/staff/',
    path: '/admin/staff/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminScheduleIndexRoute =
  DashboardAdminScheduleIndexRouteImport.update({
    id: '/admin/schedule/',
    path: '/admin/schedule/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminParentsIndexRoute =
  DashboardAdminParentsIndexRouteImport.update({
    id: '/admin/parents/',
    path: '/admin/parents/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminFeesIndexRoute = DashboardAdminFeesIndexRouteImport.update({
  id: '/admin/fees/',
  path: '/admin/fees/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminBatchesIndexRoute =
  DashboardAdminBatchesIndexRouteImport.update({
    id: '/admin/batches/',
    path: '/admin/batches/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminAttendanceIndexRoute =
  DashboardAdminAttendanceIndexRouteImport.update({
    id: '/admin/attendance/',
    path: '/admin/attendance/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStaffStudentsStudentIdRoute =
  DashboardStaffStudentsStudentIdRouteImport.update({
    id: '/staff/students/$studentId',
    path: '/staff/students/$studentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminStudentsStudentIdRoute =
  DashboardAdminStudentsStudentIdRouteImport.update({
    id: '/admin/students/$studentId',
    path: '/admin/students/$studentId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-institute': typeof AuthRegisterInstituteRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/super-admin/': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/students/$studentId': typeof DashboardAdminStudentsStudentIdRoute
  '/dashboard/staff/students/$studentId': typeof DashboardStaffStudentsStudentIdRoute
  '/dashboard/admin/attendance/': typeof DashboardAdminAttendanceIndexRoute
  '/dashboard/admin/batches/': typeof DashboardAdminBatchesIndexRoute
  '/dashboard/admin/fees/': typeof DashboardAdminFeesIndexRoute
  '/dashboard/admin/parents/': typeof DashboardAdminParentsIndexRoute
  '/dashboard/admin/schedule/': typeof DashboardAdminScheduleIndexRoute
  '/dashboard/admin/staff/': typeof DashboardAdminStaffIndexRoute
  '/dashboard/admin/students/': typeof DashboardAdminStudentsIndexRoute
  '/dashboard/admin/study-logs/': typeof DashboardAdminStudyLogsIndexRoute
  '/dashboard/staff/students/': typeof DashboardStaffStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-institute': typeof AuthRegisterInstituteRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexRoute
  '/dashboard/parent': typeof DashboardParentIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
  '/dashboard/super-admin': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/students/$studentId': typeof DashboardAdminStudentsStudentIdRoute
  '/dashboard/staff/students/$studentId': typeof DashboardStaffStudentsStudentIdRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceIndexRoute
  '/dashboard/admin/batches': typeof DashboardAdminBatchesIndexRoute
  '/dashboard/admin/fees': typeof DashboardAdminFeesIndexRoute
  '/dashboard/admin/parents': typeof DashboardAdminParentsIndexRoute
  '/dashboard/admin/schedule': typeof DashboardAdminScheduleIndexRoute
  '/dashboard/admin/staff': typeof DashboardAdminStaffIndexRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsIndexRoute
  '/dashboard/admin/study-logs': typeof DashboardAdminStudyLogsIndexRoute
  '/dashboard/staff/students': typeof DashboardStaffStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-institute': typeof AuthRegisterInstituteRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexRoute
  '/dashboard/parent/': typeof DashboardParentIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/super-admin/': typeof DashboardSuperAdminIndexRoute
  '/dashboard/admin/students/$studentId': typeof DashboardAdminStudentsStudentIdRoute
  '/dashboard/staff/students/$studentId': typeof DashboardStaffStudentsStudentIdRoute
  '/dashboard/admin/attendance/': typeof DashboardAdminAttendanceIndexRoute
  '/dashboard/admin/batches/': typeof DashboardAdminBatchesIndexRoute
  '/dashboard/admin/fees/': typeof DashboardAdminFeesIndexRoute
  '/dashboard/admin/parents/': typeof DashboardAdminParentsIndexRoute
  '/dashboard/admin/schedule/': typeof DashboardAdminScheduleIndexRoute
  '/dashboard/admin/staff/': typeof DashboardAdminStaffIndexRoute
  '/dashboard/admin/students/': typeof DashboardAdminStudentsIndexRoute
  '/dashboard/admin/study-logs/': typeof DashboardAdminStudyLogsIndexRoute
  '/dashboard/staff/students/': typeof DashboardStaffStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/unauthorized'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register-institute'
    | '/auth/update-password'
    | '/dashboard/'
    | '/dashboard/admin/'
    | '/dashboard/analytics/'
    | '/dashboard/parent/'
    | '/dashboard/staff/'
    | '/dashboard/student/'
    | '/dashboard/super-admin/'
    | '/dashboard/admin/students/$studentId'
    | '/dashboard/staff/students/$studentId'
    | '/dashboard/admin/attendance/'
    | '/dashboard/admin/batches/'
    | '/dashboard/admin/fees/'
    | '/dashboard/admin/parents/'
    | '/dashboard/admin/schedule/'
    | '/dashboard/admin/staff/'
    | '/dashboard/admin/students/'
    | '/dashboard/admin/study-logs/'
    | '/dashboard/staff/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register-institute'
    | '/auth/update-password'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/parent'
    | '/dashboard/staff'
    | '/dashboard/student'
    | '/dashboard/super-admin'
    | '/dashboard/admin/students/$studentId'
    | '/dashboard/staff/students/$studentId'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/batches'
    | '/dashboard/admin/fees'
    | '/dashboard/admin/parents'
    | '/dashboard/admin/schedule'
    | '/dashboard/admin/staff'
    | '/dashboard/admin/students'
    | '/dashboard/admin/study-logs'
    | '/dashboard/staff/students'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/unauthorized'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register-institute'
    | '/auth/update-password'
    | '/dashboard/'
    | '/dashboard/admin/'
    | '/dashboard/analytics/'
    | '/dashboard/parent/'
    | '/dashboard/staff/'
    | '/dashboard/student/'
    | '/dashboard/super-admin/'
    | '/dashboard/admin/students/$studentId'
    | '/dashboard/staff/students/$studentId'
    | '/dashboard/admin/attendance/'
    | '/dashboard/admin/batches/'
    | '/dashboard/admin/fees/'
    | '/dashboard/admin/parents/'
    | '/dashboard/admin/schedule/'
    | '/dashboard/admin/staff/'
    | '/dashboard/admin/students/'
    | '/dashboard/admin/study-logs/'
    | '/dashboard/staff/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterInstituteRoute: typeof AuthRegisterInstituteRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-institute': {
      id: '/auth/register-institute'
      path: '/auth/register-institute'
      fullPath: '/auth/register-institute'
      preLoaderRoute: typeof AuthRegisterInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/super-admin/': {
      id: '/dashboard/super-admin/'
      path: '/super-admin'
      fullPath: '/dashboard/super-admin/'
      preLoaderRoute: typeof DashboardSuperAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/student'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/staff'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parent/': {
      id: '/dashboard/parent/'
      path: '/parent'
      fullPath: '/dashboard/parent/'
      preLoaderRoute: typeof DashboardParentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/students/': {
      id: '/dashboard/staff/students/'
      path: '/staff/students'
      fullPath: '/dashboard/staff/students/'
      preLoaderRoute: typeof DashboardStaffStudentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/study-logs/': {
      id: '/dashboard/admin/study-logs/'
      path: '/admin/study-logs'
      fullPath: '/dashboard/admin/study-logs/'
      preLoaderRoute: typeof DashboardAdminStudyLogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/students/': {
      id: '/dashboard/admin/students/'
      path: '/admin/students'
      fullPath: '/dashboard/admin/students/'
      preLoaderRoute: typeof DashboardAdminStudentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/staff/': {
      id: '/dashboard/admin/staff/'
      path: '/admin/staff'
      fullPath: '/dashboard/admin/staff/'
      preLoaderRoute: typeof DashboardAdminStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/schedule/': {
      id: '/dashboard/admin/schedule/'
      path: '/admin/schedule'
      fullPath: '/dashboard/admin/schedule/'
      preLoaderRoute: typeof DashboardAdminScheduleIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/parents/': {
      id: '/dashboard/admin/parents/'
      path: '/admin/parents'
      fullPath: '/dashboard/admin/parents/'
      preLoaderRoute: typeof DashboardAdminParentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/fees/': {
      id: '/dashboard/admin/fees/'
      path: '/admin/fees'
      fullPath: '/dashboard/admin/fees/'
      preLoaderRoute: typeof DashboardAdminFeesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/batches/': {
      id: '/dashboard/admin/batches/'
      path: '/admin/batches'
      fullPath: '/dashboard/admin/batches/'
      preLoaderRoute: typeof DashboardAdminBatchesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/attendance/': {
      id: '/dashboard/admin/attendance/'
      path: '/admin/attendance'
      fullPath: '/dashboard/admin/attendance/'
      preLoaderRoute: typeof DashboardAdminAttendanceIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/students/$studentId': {
      id: '/dashboard/staff/students/$studentId'
      path: '/staff/students/$studentId'
      fullPath: '/dashboard/staff/students/$studentId'
      preLoaderRoute: typeof DashboardStaffStudentsStudentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/students/$studentId': {
      id: '/dashboard/admin/students/$studentId'
      path: '/admin/students/$studentId'
      fullPath: '/dashboard/admin/students/$studentId'
      preLoaderRoute: typeof DashboardAdminStudentsStudentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAnalyticsIndexRoute: typeof DashboardAnalyticsIndexRoute
  DashboardParentIndexRoute: typeof DashboardParentIndexRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
  DashboardSuperAdminIndexRoute: typeof DashboardSuperAdminIndexRoute
  DashboardAdminStudentsStudentIdRoute: typeof DashboardAdminStudentsStudentIdRoute
  DashboardStaffStudentsStudentIdRoute: typeof DashboardStaffStudentsStudentIdRoute
  DashboardAdminAttendanceIndexRoute: typeof DashboardAdminAttendanceIndexRoute
  DashboardAdminBatchesIndexRoute: typeof DashboardAdminBatchesIndexRoute
  DashboardAdminFeesIndexRoute: typeof DashboardAdminFeesIndexRoute
  DashboardAdminParentsIndexRoute: typeof DashboardAdminParentsIndexRoute
  DashboardAdminScheduleIndexRoute: typeof DashboardAdminScheduleIndexRoute
  DashboardAdminStaffIndexRoute: typeof DashboardAdminStaffIndexRoute
  DashboardAdminStudentsIndexRoute: typeof DashboardAdminStudentsIndexRoute
  DashboardAdminStudyLogsIndexRoute: typeof DashboardAdminStudyLogsIndexRoute
  DashboardStaffStudentsIndexRoute: typeof DashboardStaffStudentsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAnalyticsIndexRoute: DashboardAnalyticsIndexRoute,
  DashboardParentIndexRoute: DashboardParentIndexRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
  DashboardSuperAdminIndexRoute: DashboardSuperAdminIndexRoute,
  DashboardAdminStudentsStudentIdRoute: DashboardAdminStudentsStudentIdRoute,
  DashboardStaffStudentsStudentIdRoute: DashboardStaffStudentsStudentIdRoute,
  DashboardAdminAttendanceIndexRoute: DashboardAdminAttendanceIndexRoute,
  DashboardAdminBatchesIndexRoute: DashboardAdminBatchesIndexRoute,
  DashboardAdminFeesIndexRoute: DashboardAdminFeesIndexRoute,
  DashboardAdminParentsIndexRoute: DashboardAdminParentsIndexRoute,
  DashboardAdminScheduleIndexRoute: DashboardAdminScheduleIndexRoute,
  DashboardAdminStaffIndexRoute: DashboardAdminStaffIndexRoute,
  DashboardAdminStudentsIndexRoute: DashboardAdminStudentsIndexRoute,
  DashboardAdminStudyLogsIndexRoute: DashboardAdminStudyLogsIndexRoute,
  DashboardStaffStudentsIndexRoute: DashboardStaffStudentsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterInstituteRoute: AuthRegisterInstituteRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
